format = """$all$line_break$character"""

[character]
success_symbol = '[îª¶](cyan)'
error_symbol = '[îª¶](red)'

[memory_usage]
disabled = false
style = "dimmed white"

[directory]
style = "cyan"

[git_status]
style = "purple"

[git_branch]
style = "purple"

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[erlang]
symbol = "â“” "

[nodejs]
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š "

[aws]
force_display = true

[kubernetes]
disabled=false
format = '[$symbol$user/$context( \($namespace\))]($style) in '	
detect_env_vars = ["OC_LOGGED_IN"]

[[kubernetes.contexts]]
context_pattern = ".*/api-(?P<cluster>\\w+).*"
context_alias = "$cluster"
user_pattern = "(?P<username>.*)/.*"
user_alias = "$username"

# DISABLED

[gcloud]
disabled = true

[kotlin]
disabled = true

[swift]
disabled = true
